//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_EUREKA_RESTFUL_DOTNET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Cuentas = new HashSet<Cuenta>();
        }
    
        public string chr_cliecodigo { get; set; }
        public string vch_cliepaterno { get; set; }
        public string vch_cliematerno { get; set; }
        public string vch_clienombre { get; set; }
        public string chr_cliedni { get; set; }
        public string vch_clieciudad { get; set; }
        public string vch_cliedireccion { get; set; }
        public string vch_clietelefono { get; set; }
        public string vch_clieemail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cuenta> Cuentas { get; set; }
    }
}
