//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_EUREKA_RESTFUL_DOTNET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contador
    {
        public string vch_conttabla { get; set; }
        public int int_contitem { get; set; }
        public int int_contlongitud { get; set; }
    }
}
