//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_EUREKA_RESTFUL_DOTNET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cuenta()
        {
            this.Movimientoes = new HashSet<Movimiento>();
        }
    
        public string chr_cuencodigo { get; set; }
        public string chr_monecodigo { get; set; }
        public string chr_sucucodigo { get; set; }
        public string chr_emplcreacuenta { get; set; }
        public string chr_cliecodigo { get; set; }
        public decimal dec_cuensaldo { get; set; }
        public System.DateTime dtt_cuenfechacreacion { get; set; }
        public string vch_cuenestado { get; set; }
        public int int_cuencontmov { get; set; }
        public string chr_cuenclave { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Moneda Moneda { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        public virtual Empleado Empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movimiento> Movimientoes { get; set; }
    }
}
