//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_EUREKA_RESTFUL_DOTNET.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eurekabankEntities1 : DbContext
    {
        public eurekabankEntities1()
            : base("name=eurekabankEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asignado> Asignadoes { get; set; }
        public virtual DbSet<CargoMantenimiento> CargoMantenimientoes { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Contador> Contadors { get; set; }
        public virtual DbSet<CostoMovimiento> CostoMovimientoes { get; set; }
        public virtual DbSet<Cuenta> Cuentas { get; set; }
        public virtual DbSet<Empleado> Empleadoes { get; set; }
        public virtual DbSet<InteresMensual> InteresMensuals { get; set; }
        public virtual DbSet<Moneda> Monedas { get; set; }
        public virtual DbSet<Movimiento> Movimientoes { get; set; }
        public virtual DbSet<Parametro> Parametroes { get; set; }
        public virtual DbSet<Sucursal> Sucursals { get; set; }
        public virtual DbSet<TipoMovimiento> TipoMovimientoes { get; set; }
    }
}
