//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_EUREKA_RESTFUL_DOTNET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimiento
    {
        public string chr_cuencodigo { get; set; }
        public int int_movinumero { get; set; }
        public System.DateTime dtt_movifecha { get; set; }
        public string chr_emplcodigo { get; set; }
        public string chr_tipocodigo { get; set; }
        public decimal dec_moviimporte { get; set; }
        public string chr_cuenreferencia { get; set; }
    
        public virtual Cuenta Cuenta { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual TipoMovimiento TipoMovimiento { get; set; }
    }
}
