//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_EUREKA_SOAP_DOTNET
{
    using System;
    using System.Collections.Generic;
    
    public partial class InteresMensual
    {
        public string chr_monecodigo { get; set; }
        public decimal dec_inteimporte { get; set; }
    
        public virtual Moneda Moneda { get; set; }
    }
}
