//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_EUREKA_SOAP_DOTNET
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametro
    {
        public string chr_paracodigo { get; set; }
        public string vch_paradescripcion { get; set; }
        public string vch_paravalor { get; set; }
        public string vch_paraestado { get; set; }
    }
}
