//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovimientoService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomMovimientoModel", Namespace="http://schemas.datacontract.org/2004/07/WS_EUREKA_SOAP_DOTNET.Models")]
    public partial class CustomMovimientoModel : object
    {
        
        private string CodigoCuentaField;
        
        private string CodigoEmpleadoField;
        
        private string CodigoTipoMovimientoField;
        
        private string CuentaReferenciaField;
        
        private System.DateTime FechaMovimientoField;
        
        private double ImporteMovimientoField;
        
        private int NumeroMovimientoField;
        
        private string TipoDescripcionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoCuenta
        {
            get
            {
                return this.CodigoCuentaField;
            }
            set
            {
                this.CodigoCuentaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoEmpleado
        {
            get
            {
                return this.CodigoEmpleadoField;
            }
            set
            {
                this.CodigoEmpleadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoTipoMovimiento
        {
            get
            {
                return this.CodigoTipoMovimientoField;
            }
            set
            {
                this.CodigoTipoMovimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CuentaReferencia
        {
            get
            {
                return this.CuentaReferenciaField;
            }
            set
            {
                this.CuentaReferenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaMovimiento
        {
            get
            {
                return this.FechaMovimientoField;
            }
            set
            {
                this.FechaMovimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ImporteMovimiento
        {
            get
            {
                return this.ImporteMovimientoField;
            }
            set
            {
                this.ImporteMovimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroMovimiento
        {
            get
            {
                return this.NumeroMovimientoField;
            }
            set
            {
                this.NumeroMovimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDescripcion
        {
            get
            {
                return this.TipoDescripcionField;
            }
            set
            {
                this.TipoDescripcionField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MovimientoService.IMovimientoService")]
    public interface IMovimientoService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovimientoService/ObtenerMovimientosPorCuenta", ReplyAction="http://tempuri.org/IMovimientoService/ObtenerMovimientosPorCuentaResponse")]
        System.Threading.Tasks.Task<MovimientoService.CustomMovimientoModel[]> ObtenerMovimientosPorCuentaAsync(string codigoCuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovimientoService/RegistrarMovimiento", ReplyAction="http://tempuri.org/IMovimientoService/RegistrarMovimientoResponse")]
        System.Threading.Tasks.Task RegistrarMovimientoAsync(MovimientoService.CustomMovimientoModel movimiento);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IMovimientoServiceChannel : MovimientoService.IMovimientoService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class MovimientoServiceClient : System.ServiceModel.ClientBase<MovimientoService.IMovimientoService>, MovimientoService.IMovimientoService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MovimientoServiceClient() : 
                base(MovimientoServiceClient.GetDefaultBinding(), MovimientoServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IMovimientoService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MovimientoServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(MovimientoServiceClient.GetBindingForEndpoint(endpointConfiguration), MovimientoServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MovimientoServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MovimientoServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MovimientoServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MovimientoServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MovimientoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<MovimientoService.CustomMovimientoModel[]> ObtenerMovimientosPorCuentaAsync(string codigoCuenta)
        {
            return base.Channel.ObtenerMovimientosPorCuentaAsync(codigoCuenta);
        }
        
        public System.Threading.Tasks.Task RegistrarMovimientoAsync(MovimientoService.CustomMovimientoModel movimiento)
        {
            return base.Channel.RegistrarMovimientoAsync(movimiento);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMovimientoService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMovimientoService))
            {
                return new System.ServiceModel.EndpointAddress("http://10.40.20.105:666/MovimientoService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MovimientoServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IMovimientoService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MovimientoServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IMovimientoService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IMovimientoService,
        }
    }
}
