//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EUREKA_SOAP_DOTNET_CLIESC.CuentaReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CuentaReference.ICuentaService")]
    public interface ICuentaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuentaService/ActualizarSaldoYRegistrarMovimiento", ReplyAction="http://tempuri.org/ICuentaService/ActualizarSaldoYRegistrarMovimientoResponse")]
        bool ActualizarSaldoYRegistrarMovimiento(string codigoCuenta, string valorMovimiento, string tipo, string cuentaDest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuentaService/ActualizarSaldoYRegistrarMovimiento", ReplyAction="http://tempuri.org/ICuentaService/ActualizarSaldoYRegistrarMovimientoResponse")]
        System.Threading.Tasks.Task<bool> ActualizarSaldoYRegistrarMovimientoAsync(string codigoCuenta, string valorMovimiento, string tipo, string cuentaDest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICuentaServiceChannel : EUREKA_SOAP_DOTNET_CLIESC.CuentaReference.ICuentaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CuentaServiceClient : System.ServiceModel.ClientBase<EUREKA_SOAP_DOTNET_CLIESC.CuentaReference.ICuentaService>, EUREKA_SOAP_DOTNET_CLIESC.CuentaReference.ICuentaService {
        
        public CuentaServiceClient() {
        }
        
        public CuentaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CuentaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CuentaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CuentaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ActualizarSaldoYRegistrarMovimiento(string codigoCuenta, string valorMovimiento, string tipo, string cuentaDest) {
            return base.Channel.ActualizarSaldoYRegistrarMovimiento(codigoCuenta, valorMovimiento, tipo, cuentaDest);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarSaldoYRegistrarMovimientoAsync(string codigoCuenta, string valorMovimiento, string tipo, string cuentaDest) {
            return base.Channel.ActualizarSaldoYRegistrarMovimientoAsync(codigoCuenta, valorMovimiento, tipo, cuentaDest);
        }
    }
}
